### ISSUE TITLE
Landscape mode capture support

### ISSUE THREAD

**Issue by Piste** [LeoKlaus/Paperparrot#100]
**Is your feature request related to a problem? Please describe.**
Sometimes pages pages I scan would be better suited to landscape mode rather than portrait. 

**Describe the solution you'd like**
If I rotate my iPhone into landscape mode, make the app recognize it and adjust the capture angle. 

This is somewhat related to https://github.com/LeoKlaus/Paperparrot/issues/99

**Comment by LeoKlaus** [comment]
You can rotate the scanned image by tapping on the small preview in the bottom left. I'll have to see whether landscape support can be enabled for the scanner only, I don't intend to add landscape support for the entire app on iPhone.

**Comment by LeoKlaus** [comment]
Marking this as wontfix for now, there seems to be no way to do this in SwiftUI and a fix for #99 solves the issue IMO.
