### ISSUE TITLE
Restore purchase asks for password. No 2FA. Purchase not restored.

### ISSUE THREAD

**Issue by Piste** [LeoKlaus/Paperparrot#101]
**Describe the bug**
Is it normal that the restore purchase functionality asks for my Apple ID password but does not trigger MFA? Also it didn't work. I'm using the TestFlight version. 
Changed my Apple ID password. This is weird behavior.

**Comment by LeoKlaus** [comment]
In app purchases in TestFlight are simulated. You can just "buy" the App for free.

**Comment by tebra-jl** [comment]
Hello,
I have exactly the same bug with the apple store version.
Paperparrot version 2.2.2, iPhone 14 Pro, IOS 17.5
The restore purchase functionality asks for my Apple ID password but does not trigger MFA

**Comment by LeoKlaus** [comment]
This is not something I have any influence on. Paperparrot can only trigger the system dialog using StoreKit.

For most users, reinstalling the app helped with issues restoring the IAP.

**Comment by tebra-jl** [comment]
Ok it works by deleting and reinstalling the app.
Thanks
