### ISSUE TITLE
Cannot connect to http:// (tailscale)

### ISSUE THREAD

**Issue by Piste** [LeoKlaus/Paperparrot#103]
**Describe the bug**
I am able to connect to my Paperless NGX instance via the http:// URL while on a browser, VPN-ed via tailscale but the same is not possible in the app. I get "Couldn't connect to server". 

**Expected behavior**
I should be able to connect.

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 15.4.1 (a)
 - Version 1.3.1
 - Server Version (if applicable) [e.g. Paperless-ngx 1.11.3]

**Additional context**
Do you maybe enforce HTTPS strictly and disable http?

**Comment by Piste** [comment]
I'll try this. Thank you.

**Comment by LeoKlaus** [comment]
Did it work? If so, I'd close this.

**Comment by Piste** [comment]
Specifying IP works. Thank you!
