### ISSUE TITLE
[BUG] crash when scanning 

### ISSUE THREAD

**Issue by alva-seal** [LeoKlaus/Paperparrot#104]
**Describe the bug**
When scanning from my network scanner it sometimes crashes when the scan is finished 

**To Reproduce**
1. Go to +
2. Click on network scan
3. Scan
4. It stays at waiting for scanner u til the crash

**Expected behavior**
No crash and letting me add the scanned file

**Screenshots**
Settings of the scan:
![image](https://user-images.githubusercontent.com/2143057/236817203-a67740c6-194d-46d0-b0aa-2b464e8c4eef.png)
**Environment(please complete the following information):**
 - Device:  iPhone 12 Pro
 - OS: 16.4.1 (a)
 - Version: 1.3.1
 - Server Version (if applicable) Paperless-ngx 1.14.2

**Additional context**
Scan with a hp 4520

it does not happen every time

**Comment by LeoKlaus** [comment]
Just out of curiosity: What options can you select for file format and what format do the files have if you select octet-stream? Usually, a scanner should advertise application/pdf, not octet-stream.
My first assumption is that saving the file on disk fails as the system can't determine the file type to use. None of the scanners I tested with advertised octet-stream and I have no idea what kind of binary the scanner would send in that case.

**Comment by alva-seal** [comment]
Oh it seems it has to do with it normally I use pdf but it seams indeed to crash with octet-stream.

I can select the following:
![image](https://user-images.githubusercontent.com/2143057/236822950-8871eb9d-1d4c-4f7f-a260-a088168c8fb3.png)
But I don’t know what the file looks if I select octet stream.

**Comment by alva-seal** [comment]
If I use pdf it won’t crash as it seams
