### ISSUE TITLE
[BUG] Saved views with advanced filtering (tags, document tags) ignore the advanced filter terms

### ISSUE THREAD

**Issue by ronaldheft** [LeoKlaus/Paperparrot#108]
**Describe the bug**
In Paperless, it's possible to setup advanced views that exclude tags or offer other advanced filtering. Paperparrot gets tripped up on these views and ignores the advanced filters.

**To Reproduce**
1. In Paperless, go to the Documents tab.
2. If an existing filter is active, click the "Reset filters" link
3. Under the tags dropdown, select a tag to filter by.
4. In the list of documents that remain from the filter, find a document that has two or more tags.
5. Under the tags dropdown, also select one of the other tags from the chosen document in step 4.
6. Notice how the document from step 4 remains in the filtered list.
7. Under the tags dropdown, click the tag the you selected in step 5. This will mark the tag as an excluded tag.
8. Notice how the document from step 4 is no longer in the filtered list.
9. Save the view.
10. Open Paperparrot
11. Select the saved view.
12. Notice how Paperparrot will ignore the excluded tag in the saved view. If you compare Paperparrot and Paperless side by side, Paperparrot will include the document from step 4, while Paperless will have the document filtered out.

**Expected behavior**
Paperparrot should perform the same filtering actions that are possible in saved Paperless views.

**Screenshots**

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.5
 - Version: 1.4.0
 - Server Version: Paperless-ngx 1.15.1

**Additional context**
The example above applies to excluded tags, but the same can occur for excluded document types and other filter criteria. You can also write advanced filters in the `Advanced search` field in Paperless, which are not replicated identically in Paperparrot. For example, try writing a more advanced filter using OR criteria like so and observe how Paperparrot handles the filter:

```
(tag:Medical OR tag:Dental OR tag:Vision) NOT tag:insurance
```

**Comment by LeoKlaus** [comment]
Hi Ron, thanks for the report.
Respecting excluded tags, document types and so on should be a fairly easy fix.

I’ll see what I can do about the filters, translating these queries could get complex very quickly and I’m not familiar with this feature of Paperless.

**Comment by LeoKlaus** [comment]
The update fixing this is now live. 
There's no ready to use parser for the query language Paperless uses (Whoosh) that I could use and I don't have the time to implement a whole parser myself.
Maybe I'll find a way to at least translate some queries in the future, but for now, Advanced Search is not supported in Paperparrot.

**Comment by ronaldheft** [comment]
Awesome! Thank you for the fast turn around on this!

Completely understand about the added complexity of using the advanced search functionality. Adding in the excluded tags covers 99% of my saved views, so I'm a happy camper. I only have one view that uses an advanced query, and my need for viewing it on mobile is low.

Thanks again for making a wonderful app!
