### ISSUE TITLE
[BUG] Can not load correspondents from server

### ISSUE THREAD

**Issue by jalibu** [LeoKlaus/Paperparrot#111]
**Describe the bug**
On iOS, there is an infinite loading spinner mentioning that it loads correspondents from the server.

**To Reproduce**
1. Go to 'Documents'
2. See error

**Expected behavior**
1. Loading finalizes
2. Correspondents are displayed as filter option

**Screenshots**
<img width="525" alt="image" src="https://github.com/LeoKlaus/Paperparrot/assets/25933231/8082dcf2-311c-4d55-8477-76858e1d4aba">

**Environment(please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.5.1
 - Version 1.4.1
 - Server Version (if applicable) Paperless-ngx 1.16.5

**Additional context**
Some old correspondents are displayed. So it worked in the past.

**Comment by LeoKlaus** [comment]
How many correspondents do you have? Is this on first startup or did it work before?

**Comment by jalibu** [comment]
@LeoKlaus problem solved.
Root cause was a missing `USE_X_FORWARD_HOST=true` env to enable nginx as reverse proxy.
This caused `/api/correspondents/` to have a localhost address as next paging url. 
```
{
    "count": 28,
    "next": "http://localhost:8999/api/correspondents/?page=2",
    "previous": null,
    "all": [...],

    ...
```

It worked as long as I had <25 (non-paged) correspondents.

**Comment by LeoKlaus** [comment]
Makes sense. Thanks for the update!
