### ISSUE TITLE
[BUG] No connection to Paperless NGX Server

### ISSUE THREAD

**Issue by sascha-schieferdecker** [LeoKlaus/Paperparrot#128]
**Describe the bug**
No connection to Paperless NGX Server

**To Reproduce**

Try to connect to a local Paperless NGX server running behind Traefik secured with Letsencrypt wildcard certificate - Connection fails, only shows error message "could not connect", nothing else.

**Expected behavior**
Connect

**Screenshots**

**Environment(please complete the following information):**
- Serverurl like "https://xxx.yyy.me" - tried with and without ending slash
- Macbook with MacOS Sonoma
- Paperless-ngx 1.17.4
- Paperparrot 1.7.2

**Additional context**

Other Clients like "Less Paper" are able to connect

**Comment by LeoKlaus** [comment]
Hi Sascha,
I'm sorry for the inconvenience.
Can you make sure that https://xxx.yyy.me/api/ is reachable?
https://xxx.yyy.me should be the URL you enter in the browser to open the Paperless-ngx-Webinterface.
There should be no trailing slash and the protocol should be included, so the URL you posted looks to be formatted as Paperparrot expects it.

In some cases, a restart of the App is necessary for the initial connection to work, you may also try to quit Paperparrot via the dock or menu and reopening.

**Comment by sascha-schieferdecker** [comment]
Yes, the API is there if I visit the URL in a browser, I see a page titled with "Django REST framework" and a listing of various endpoints.

But now it worked, quitting and various retries helped...

I just bought the full version.

**Comment by LeoKlaus** [comment]
Hi Sascha,

thank you for your support and for updating the issue. Connecting really shouldn't be that cumbersome, I'm just finishing an update that should streamline the process.

If you have any feedback or feature requests, let me know!

**Comment by vednolacni** [comment]
i have the same problem and the api page is reachable. is ther esomthing else to try? i already bought a full verzion and the setup worked already but i log out of the app and now i cant get back in.

**Comment by LeoKlaus** [comment]
Hey @vednolacni, can you give me some more information?
There should be an error message specifying, why the connection didn't work. There's a button to export debug logs in the top right of the login page in Paperparrot, can you tap that after trying to log in and see if something shows up there?
Simply reinstalling the app could also help if the setup worked before.

**Comment by vednolacni** [comment]
Here is the log:

![image](https://github.com/LeoKlaus/Paperparrot/assets/123391433/ea76b4eb-1357-4a83-b404-aa2b2ca26a0b)

I tried reinstalling but its not working.

**Comment by LeoKlaus** [comment]
This seems to be a different issue than the one you replied to. I've opened a new one at #145, please continue there.
