### ISSUE TITLE
[BUG] Cannot connect to self hosted instance

### ISSUE THREAD

**Issue by neseih** [LeoKlaus/Paperparrot#129]
**Describe the bug**
Paperparrot cannot connect to self hosted instance. The instance is hosted on a domain with subpath (https://domain.example.com/doc). Slash at the end doesn‘t change anything.
Error message: The server didn‘t accept the stored token. Please log in again.
Sometime it works but documents is empty, shortly after that the error message appears.

**To Reproduce**
Log in on a self hosted server with subpath

**Environment(please complete the following information):**
 - Device: iPhone15 Pro
 - OS: iOS 17
 - Version: 1.7.2
 - Server Version: 1.17.4

**Comment by LeoKlaus** [comment]
Hi neseih,

this pops up a lot recently, I'm actively working on improving the login process and adding better debug capabilities.
Can you reach https://domain.example.com/doc/api/ in your browser?
It seems like Paperparrot is able to obtain a token from your server but receives a 401 while trying to load the data.

**Comment by neseih** [comment]
Hi LeoKlaus,

thanks for the quick reaction. I‘m able to reach that endpoint in a browser after logging in (response: Code 200 Api Root for GET /doc/api/).
The logs in Paperless NGX are empty regarding this issue

**Comment by freeurcom** [comment]
Hi neseih, hi LeoKlaus,

same issue here by the way. Cannot connect to my self-hosted paperless-ngx.
When I enter http://XXXXXX.dynv6.net:8777 and my credentials in the app, I receive "Couldn't connect to server". When I open http://XXXXXX.dynv6.net:8777/api in Safari, I get a popup where I would need to enter my credentials.

(Tried it with or without ending "/", tried it in my local network and in an external one)
Edit: Saw your post on issue #110, but I checked the correct URL and credentials several times.

**Comment by LeoKlaus** [comment]
I've just uploaded a new build with better debugging and an improved login flow to testflight, once its approved, I'll let you know.
@freeurcom http connections to remote instances are not supported. You'll either have have to use HTTPS via Letsencrypt or connect locally via the IP:Port of your server.

**Comment by pkoerner81929** [comment]
Same here. Using http for self hosted instance connected through tailscale. 

http://personal.tailscale.meshvpnip.address:8000 

does not connect. 

Works from within browser.

**Comment by freeurcom** [comment]
Hi LeoKlaus, hi pkoerner81929,

the suggested solution here works great:
> ... @freeurcom http connections to remote instances are not supported. You'll either have have to use HTTPS via Letsencrypt or connect locally via the IP:Port of your server. ...

I used the direct http://IP:Port option and it works perfectly.
I won't go for the other option with the CA as I usually scan documents only at home - and if, I would use the iOS tools to scan a document and put it into the consume folder of my paperless-ngx (via Google Drive).

**Comment by LeoKlaus** [comment]
Hi @freeurcom and @pkoerner81929, the issues regarding connection via Tailscale are separate from what neseih reported. I've created an additional issue for connections via Tailscale at #131. If you have any additional questions or information, please post them there.

**Comment by LeoKlaus** [comment]
Hey again @neseih, the issue was probably caused by the way the access token was stored in KeyChain. This should be fixed with 1.7.4 which is coming in the next few days.
I'll leave the issue open for now, so you can confirm whether it's resolved once the update arrives.
Thank you for the information and the bug report!

**Comment by LeoKlaus** [comment]
Quick update: 1.7.4 was released today, hope it works now!

**Comment by benjamira** [comment]
Hi LeoKlaus, 
Unfortunately it still does not work for me.
I use an internal CA which is installed in my apple keychain, but Paperparrot does not seem to accept that. Would be nice to be able to explicitly accept a connection with an unknown (or self signed) certificate.

Message (translated to English):
The certificate for this server is not valid.
Maybe a connection with a Server ist established, which pretends to be "my.internal.domain" and which is a danger to confidential data.


Log:
[6.10.2023, 23:38] [CoreDataHandler] Initializing store without iCloud support
[6.10.2023, 23:38] [CoreDataHandler] CoreData store initialized
[6.10.2023, 23:38] [ApiHandler] Connecting to <private>
[6.10.2023, 23:38] [KeychainHandler] Keychain item for service <private> and account <private> not found
[6.10.2023, 23:38] [ApiHandler] Obtaining token...
[6.10.2023, 23:39] [ApiHandler] URLSession returned error: <private>
Tried connecting to: <private>/api/token/

**Comment by LeoKlaus** [comment]
Hey @benjamira, I’ve moved this to #135 as your issue is not related to this one.

**Comment by neseih** [comment]
Hi @LeoKlaus 
Thanks for the update.

It works now as expected. Have a great weekend!
