### ISSUE TITLE
[BUG] Connections via Tailscale not working

### ISSUE THREAD

**Issue by LeoKlaus** [LeoKlaus/Paperparrot#131]
Seems like Tailscale and Paperparrot don't play nice at the moment.

I've never used Tailscale, so I'll have to set it up to test this but I was under the assumption that it is (like other VPNs) transparent to the client (read: behaving like a local connection).

I've definitely had users successfully connect via Tailscale in the past.

I'm actively investigating and working on a fix. Still, additional information is always helpful.

**Comment by LeoKlaus** [comment]
I've found the issue causing Tailscale configurations not to work.

To my surprise, Tailscale assigns new IPs to connected devices that are (and that's pretty weird, IMO) _not_ in any of the defined ranges for local IPs. App Transport Security (rightly so) blocks plain-text connections to these IPs.
I've disabled App Transport Security for now, but this also allows plain HTTP connections to _acutally_ remote targets. I strongly advice anyone *not* to use HTTP to connect to a remote instance. Always use HTTPS or a VPN.

**Comment by Piste** [comment]
It seems like I'm stuck if I want to use Paperparrot on the go. 
My VPN protocol is Wireguard, as orchestrated by Tailscale.
Would Paperparrot work if I (somehow) give my Paperless instance a local-only HTTPS config?
I do not want to expose my Paperless-NGX instance to the public internet.
I'm curious what your recommendation is @LeoKlaus

**Comment by LeoKlaus** [comment]
Hi Piste, a local only HTTPS config is very hard to do properly and shouldn't be necessary.

Are you already on 1.7.4 of Paperparrot? The update released yesterday. If so, please tap the Log button in the top right after trying to sign in and post the logs (also the error message you see).
Here's what the button looks like:
![image](https://github.com/LeoKlaus/Paperparrot/assets/66492595/be9c77b4-c594-4bd1-acfe-f66ba1e747c0)


I've disabled the requirement for HTTPS for remote targets to support Tailscale better, so that shouldn't be an issue.
You should be able to use http:{tailscale-ip}:{port} to connect.

**Comment by Piste** [comment]
Ah it's all fixed now. I can connect to the server and upload scans. Brilliant! Thank you very much. 

Feel free to close this issue if I was the only one reporting issues.

**Comment by LeoKlaus** [comment]
Great, I'll close this, then.
