### ISSUE TITLE
[BUG] Syncing documents with the server is not being executed

### ISSUE THREAD

**Issue by mattes8612** [LeoKlaus/Paperparrot#132]
**Describe the bug**
During synchronization, the documents are endlessly loading (1 new document on the server). Tags, correspondents, etc., take a long time. "Loading documents from server" is displayed permanently. Server CPU utilization is higher than normal.

Initial synchronization worked without problems yesterday.

**To Reproduce**

New document on server. Start sync in the app by "pulling down" on the documents tab.

**Expected behavior**
Quick synchronization with server

**Environment (please complete the following information):**
- Device: iPhone 11
- OS: iOS 17.0.2
- Server Version: Paperless-ngx 1.17.4 in docker container

**Additional context**
This issue did not occur yesterday. The server was not changed.

**Comment by LeoKlaus** [comment]
Hi mattes,

how many documents are on your server? Pulling down refreshes all documents, not just new ones.
With a large number of documents, this could take while.

**Comment by mattes8612** [comment]
Hey thanks for the quick reply. I’ve got round about 1700 docs. Not only pulling down but also starting the app lead to the effect of endless loading time. Tried the last 2 hours to get my latest doc synced in the app. No end in sight at the moment.

**Comment by LeoKlaus** [comment]
I'll see how I can improve this. The main issue is that Paperless doesn't offer any sort of changelog or anything, so the only way to have the offline database stay current is regularly syncing *all* documents in full.

What I can definitely do is add a better indication of progress and a toggle to switch from full synchronisation to some sort of on-demand-loading. That would mean that the offline functionality of Paperparrot (mainly Search and Spotlight Indexing) would potentially have to use outdated data.

Can you try heading to https://your-instance/api/documents/ and see how fast that loads?

**Comment by mattes8612** [comment]
Hello, the page loads very fast. Just changed the server and used directly the IP Adress. Loaded all the documents fast - also the new one. Search works fast. But still got „lade Dokumente von Server“. Like something doesn’t fit. Also noticed that „benutzerdefinierte Ansichten“ stays empty.

**Comment by LeoKlaus** [comment]
Were you using Tailscale or another VPN before? If all the data was routed through the internet, that could significantly impact transfer speed.

Custom views are loaded last, after all documents, so it makes sense that those don't show up when the documents sync never finishes.

Until I manage to improve the update process, the only advice I can really give you is trying to let it completely sync once on your local network.

I'm really sorry for the inconvenience. Thank you for all the information.

**Comment by mattes8612** [comment]
Didn’t use vpn. I’m testing it directly in my network: first traefik-> then hostname-> now IP

Thanks for the advice.

You’re welcome.

**Comment by xxLeoxx93** [comment]
Same issue here. Also Paperless in docker (in my case ~4k Documents, Paperless-ngx 1.17.4). 
Loading takes very long which is a bit anoying if you just want to check if a new document was added.
The API link loads for ~2sec for me.
The official "paperless" app doesn't to load for long.

**Comment by LeoKlaus** [comment]
> The API link loads for ~2sec for me.

That's ~2sec per request, with each request serving 50 documents. To sync the entire database, you're looking at 160 seconds.
I can't really improve anything there, that's just Paperless being slow (it's not a matter of your server being slow, Paperless just has trouble with that many files).

The official Paperless app (just like the webinterface) loads data on-demand and has no offline functionality. They're fundamentally different from Paperparrot in that regard.

As I said, I'll try to optimize this as much as possible with the next update, especially improving feedback on the sync process. But its either have accurate offline data or fast load times, both is not possible with that many documents.

**Comment by xxLeoxx93** [comment]
Hey!
from what I see in the response it shows a list of all IDs and then the details of the first like 50 documents or so.
Would it be possible maybe to adjust the loading message? just based on the documents list it should be feasable to detect new documents and show a message like "Downloading Metadata for 5 new documents" for example.
Also if the new documents are downloaded before the rest of the documents is checked for changes would be great

Something like that would be helpfull because you could easily see if new documents are there or not and in most cases (I think) you either search for something or you want to see the latest documents that have been added by mail automaticly for example.

Thanks anyways!

**Comment by LeoKlaus** [comment]
> shows a list of all IDs and then the details of the first like 50 documents or so.

Yes. I suspect the list of all IDs is what makes responses so slow (they were much faster a few months ago), but the API documentation doesn't mention any way to disable this.

> Just based on the documents list it should be feasable to detect new documents and show a message like "Downloading Metadata for 5 new documents" for example. Also if the new documents are downloaded before the rest of the documents is checked for changes would be great

That's a pretty good idea. I'll have to check when the full list was first added in order to keep support for older versions of Paperless, but that's definitely possible.

**Comment by xxLeoxx93** [comment]
Got the update today - I've to say it's absolutly amazing! Thanks a lot. Btw: Is an android app planned? I mean there are alternatives but it's always nice to use the same app on multiple devices.

**Comment by LeoKlaus** [comment]
Glad it helped. I wont mark this as closed just yet as there can still be some issues with slow responding servers (my test instance with ~2700 documents takes about 20s per API request and won't load all documents without timeouts).

>Btw: Is an android app planned? I mean there are alternatives but it's always nice to use the same app on multiple devices.

Not as of now. Paperparrot is written entirely in Swift and SwiftUI and heavily relies on Apples proprietary frameworks like Core Data and Keychain.
It would certainly be possible to build something similar on Android, but it would be an entirely different app on a different codebase.  The biggest issue is - honestly - that I haven't used an Android device in years and I would have no idea how to make an app feel native there. I appreciate your interest, though :)

**Comment by LeoKlaus** [comment]
Marking this as closed as 1.8.0 addressed this.
@mattes8612 If you're still having issues loading saved views, please reopen this issue.
