### ISSUE TITLE
Support for self-signed certificates

### ISSUE THREAD

**Issue by LeoKlaus** [LeoKlaus/Paperparrot#135]
Hi LeoKlaus, 
Unfortunately it still does not work for me.
I use an internal CA which is installed in my apple keychain, but Paperparrot does not seem to accept that. Would be nice to be able to explicitly accept a connection with an unknown (or self signed) certificate.

Message (translated to English):
The certificate for this server is not valid.
Maybe a connection with a Server ist established, which pretends to be "my.internal.domain" and which is a danger to confidential data.

Log:
[6.10.2023, 23:38] [CoreDataHandler] Initializing store without iCloud support
[6.10.2023, 23:38] [CoreDataHandler] CoreData store initialized
[6.10.2023, 23:38] [ApiHandler] Connecting to <private>
[6.10.2023, 23:38] [KeychainHandler] Keychain item for service <private> and account <private> not found
[6.10.2023, 23:38] [ApiHandler] Obtaining token...
[6.10.2023, 23:39] [ApiHandler] URLSession returned error: <private>
Tried connecting to: <private>/api/token/

_Originally posted by @benjamira in https://github.com/LeoKlaus/Paperparrot/issues/129#issuecomment-1751434876_

**Comment by LeoKlaus** [comment]
This is probably a rather sizable task. I’ll see what I can do, but I can’t give you any timeline or promises.

**Comment by benjamira** [comment]
Hi LeoKlaus,
that's fine for me. I solved it by implementing an official Letsencrypt certificate in my local environment. So, currently PaperParrot works fine for me. Nice job!

**Comment by LeoKlaus** [comment]
Great to hear, thank you!

**Comment by LeoKlaus** [comment]
Wontfix for now...

**Comment by drunkdev1991** [comment]
Is there any news on that? I´d like to use it in air gapped network. This will be really bugging me to bring in public ssl certs...
sorry to bother

**Comment by LeoKlaus** [comment]
> Is there any news on that? I´d like to use it in air gapped network. This will be really bugging me to bring in public ssl certs... sorry to bother

This should already work as long as the root certificate is trusted on your device.

Edit: Accepting untrusted certs is not something I plan to ever implement.
