### ISSUE TITLE
iCloud Synch not working

### ISSUE THREAD

**Issue by christianblust** [LeoKlaus/Paperparrot#141]
Hi, 

I just bought your app and installed on my m1 macbook air 2020 and the mobile app on the iphone 13 mini. As I understand the product it should work without an actual paperless nx server? I tried synching documents I added on my macbook air to my iphone via icloud and vice versa. I see that there is a new document with the title etc, however, upon opening the actual document I get an endless rotating spinner and the message "document could not be loaded, are you connected to the internet?". Please mind I have just two documents, one added via macbook and the other via my iphone. Both see both documents but can only view the one they actually added. So the synching via icloud is not working for me I guess.

**Comment by LeoKlaus** [comment]
That sounds like a bug. What versions of macOS and iOS are you running? Can you go to the settings in Paperparrot and click on "Get Debug Logs" after trying to open one of the affected documents?

**Comment by LeoKlaus** [comment]
Closing this for now. If the issue still persists, please reopen.

**Comment by nerdware-timmmi** [comment]
I getting the same issue in the actual version (2.1.2)

My setup is:
- add a pdf from iCloud finder app on my ipad
- try to open this document on my iphone
- Get "document could not be loaded, are you connected to the internet?"
- no Paperless-ngx Server is configured
