### ISSUE TITLE
[BUG] Document viewer not opening on search tab even when option selected

### ISSUE THREAD

**Issue by bandundu** [LeoKlaus/Paperparrot#142]
**Describe the bug**
When searching for documents through the search tab in the Paperparrot app on my iPhone, the document editor opens instead of the document viewer, despite having selected "View documents in viewer" in the settings.

**To Reproduce**
1. Go to 'Search Tab' on Paperparrot iPhone app.
2. Search for any document.
3. Click on the desired document from the search results.
4. Document editor opens instead of document viewer.

**Expected behavior**
I expect the document viewer to open when I click on a document in the search tab, as I have selected "View documents in viewer" in the settings.

**Environment(please complete the following information):**
- Device: iPhone 13 Pro Max
- OS: iOS 17.0.3
- Version: Paperparrot 1.7.5
- Server Version: Paperless-ngx 1.17.4

**Additional context**
This issue does not occur when I am on the "Documents" page; it only happens when I am on the "Search" tab.

**Comment by LeoKlaus** [comment]
Hi Bandundu,

thanks for reporting this, I'll fix it with the next update.
