### ISSUE TITLE
[Feature Request] Add setting to search content by default

### ISSUE THREAD

**Issue by bandundu** [LeoKlaus/Paperparrot#143]
**Is your feature request related to a problem? Please describe.**
Yes, it's related to the search functionality in the Paperparrot app. I find it frustrating to manually enable "In-text search" for every individual search query. The titles of my documents are often not useful because they are scanned and OCR'd without a reliable way to set the title.

**Describe the solution you'd like**
I'd like an option to set "In-text search" to be always enabled by default for all my searches in the app.

**Comment by LeoKlaus** [comment]
This is pretty simple, I'll see to have it ready for the next release.
