### ISSUE TITLE
App 'bought' as family member does not load more then 250 documents

### ISSUE THREAD

**Issue by JoeRu** [LeoKlaus/Paperparrot#144]
**Describe the bug**
I bought the app premium feature. Then installed it for a family member. The premium isn't available to buy but still the app behaves as it were in demo modus and not load more then 150
Documents. 

**To Reproduce**
1. buy app / premium on first account
2. buy app on family member account
3. try to load / stops at 250 documents

**Expected behavior**
Should work as expected when bought. 

**Screenshots**

**Environment(please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Version 17
 - Server Version Paperless-ngx 1.17.4

**Additional context**

**Comment by LeoKlaus** [comment]
Hi Johannes, thanks for reaching out and sorry for the troubles.
This is not related to unlocking the full version. If Paperparrot displays more than 6 documents and the In-App-Purchase isn't available in settings, it's already unlocked.

What you're describing sounds like not all documents were synchronised properly. How many documents are on your server? The initial load can take quite some time depending on the number of documents, connection speed and overall speed of your server.

**Comment by JoeRu** [comment]
Hi. Yes. It shows more then 6 documents. The server has about 2000 documents. On my device it loads them in about 10 seconds. On my wife phone it stops exactly by 250.

**Comment by LeoKlaus** [comment]
> The server has about 2000 documents.

On my (fairly fas) test instance with ~4000 documents, the initial load/synchronisation takes about 5 minutes.

> On my device it loads them in about 10 seconds. On my wife phone it stops exactly by 250.

After the first (full) sync, Paperparrot only fetches changes. This is expected to be much faster than the initial full sync.

Paperparrot keeps a full local copy of the entire database, this way it can perform search locally (much faster) and when not connected to the server.
For this to work, it has to download all data for every single document once when setting up the connection.

As long as the little spinner in the top of the documents overview spins, Paperparrot is still downloading documents (you should get a status update including how many documents were already fetched).

If that spinner disappeared before all documents were loaded and a restart of the app doesn't help, there's a button in the settings to manually perform a full sync with the server. Another option would be to hit "Switch Server" and connect to the same server again (this will completely redo the synchronisation, including attributes and custom views).

If that doesn't help, please let me know.

**Comment by JoeRu** [comment]
Ok. I checked. There is some errors in the debug logs

I don't really understand why it is working on my device (iPhone 13 pro) and not on my spouses iPhone 12. 

[20.10.2023, 16:31] [ApiHandler] received unexpected response from server while fetching users: 403
[20.10.2023, 16:31] [ApiHandler] received unexpected response from server while fetching storage paths: 403
[20.10.2023, 16:32] [ApiHandler] received unexpected response from server while fetching users: 403
[20.10.2023, 16:32] [ApiHandler] received unexpected response from server while fetching storage paths: 403
[20.10.2023, 16:32] [ApiHandler] received unexpected response from server while fetching users: 403
[20.10.2023, 16:32] [ApiHandler] received unexpected response from server while fetching storage paths: 403
[20.10.2023, 16:32] [NewSettingsView] couldn't delete document folder: Error Domain=NSCocoaErrorDomain Code=4 UserInfo={NSUserStringVariant=<private>, NSFilePath=<private>, NSUnderlyingError=0x2806f20a0 {Error Domain=NSPOSIXErrorDomain Code=2}}
[20.10.2023, 16:32] [Paperparrot_App] No token found
[20.10.2023, 16:32] [CloudDataHandler] error copying files: Error Domain=NSCocoaErrorDomain Code=260 UserInfo={NSFilePath=<private>, NSUnderlyingError=0x28069f510 {Error Domain=NSPOSIXErrorDomain Code=2}}
[20.10.2023, 16:33] [ApiHandler] server responded: 200
[20.10.2023, 16:33] [ApiHandler] received unexpected response from server while fetching users: 403
[20.10.2023, 16:33] [ApiHandler] received unexpected response from server while fetching users: 403

**Comment by LeoKlaus** [comment]
The 403s suggest that the user you're using with Paperparrot has no access to the documents (and tags, correspondents, etc.) or no userdata is supplied.

Do you and your spouse use the same Paperless user? Can you check the server logs?

**Comment by JoeRu** [comment]
Ok. It was authorization. It's a bit unclear what set authorization needs to be set minimal for a read only access. But that's something maybe to be documented somewhere. For today thanks for the fast support.

**Comment by LeoKlaus** [comment]
> It's a bit unclear what set authorization needs to be set minimal for a read only access. But that's something maybe to be documented somewhere. For today thanks for the fast support.

Glad it works now! Actually, I have no idea what permissions need to be active and this has been (seemingly) inconsistent in my testing. Paperparrot does access the default /api/ endpoints, i.e. documents/, correspondents/, tags/, etc. for all operations.

The only "non-standard"-Endpoint that Paperparrot interacts with is /api/token/ to obtain an authorization token, but there's no documentation on whether or not this requires any permissions. In general, the documentation around permissions is a bit lackluster.
