### ISSUE TITLE
[BUG] Version 1.8.1 Documents page says "Fetching users from server", documents don't upload beyond 0.0% 

### ISSUE THREAD

**Issue by Piste** [LeoKlaus/Paperparrot#149]
**Describe the bug**
Documents page says "Fetching users from server", documents don't upload beyond 0.0% 

**To Reproduce**
I didn't touch my server details. Still connecting to http://{IPv4 address} via Tailscale

**Expected behavior**
Documents should upload and the Documents page should refresh with the latest

**Screenshots**
![IMG_C8254BD839F8-1](https://github.com/LeoKlaus/Paperparrot/assets/5099194/4630a259-2da6-4b95-8711-f2a8d34b5644)

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.1
 - Version 1.8.1
 - Server Version 1.17.4

**Comment by LeoKlaus** [comment]
Hi Piste, can you let it load for about 30 seconds and then export the debug logs? The button to do so is in the "App Settings" section of the settings in Paperparrot.

**Comment by Piste** [comment]
I got this:
```
[11/3/2023, 23:19] [CoreDataHandler] Initializing store without iCloud support
[11/3/2023, 23:19] [CoreDataHandler] CoreData store initialized
[11/3/2023, 23:19] [StoreKitHandler] unlocked!
```

**Comment by LeoKlaus** [comment]
Nothing else? Looks like the sync process never starts.

Did you set a startup tab other than "Documents"?

Can you try using pull to refresh gesture in the "Documents" tab (just pull down on any document until the small spinner above the search bar appears)? That should trigger the syncing process manually.

**Comment by Piste** [comment]
Pulling to refresh generates the same log.
I haven't changed my Startup Tab, it is still Documents.

**Comment by Piste** [comment]
Let me know what else I can do to help troubleshoot.
I might just uninstall and reinstall...

**Comment by LeoKlaus** [comment]
Try reinstalling. If that doesn't help, can you check if the same issue occurs in the App Store version?

**Comment by Piste** [comment]
This is what the App Store app says upon fresh install and server config. I'm using http to a Tailscale IP:
```

[11/6/2023, 20:20] [Paperparrot_App] No token found
[11/6/2023, 20:20] [CloudDataHandler] error copying files: Error Domain=NSCocoaErrorDomain Code=260 UserInfo={NSFilePath=<private>, NSUnderlyingError=0x2823105d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[11/6/2023, 20:23] [ApiHandler] Connecting to <private>
[11/6/2023, 20:23] [ApiHandler] Token read from keychain!
[11/6/2023, 20:23] [StoreKitHandler] unlocked!
[11/6/2023, 20:24] [DocumentsView] Finished updating groups
[11/6/2023, 20:24] [DocumentsView] Finished updating groups
```
And here is what the UI looks like:
![image](https://github.com/LeoKlaus/Paperparrot/assets/5099194/7ba7b905-f3cc-435b-8d4d-1a92f6a45a11)

**Comment by LeoKlaus** [comment]
Does anything appear in your server logs? Can you try if connecting without Tailscale works? Do you have another device on hand to test with?

**Comment by LeoKlaus** [comment]
I'll close this for now. If the issue persists, please reopen.
