### ISSUE TITLE
[BUG] Could not load document

### ISSUE THREAD

**Issue by jrnewell** [LeoKlaus/Paperparrot#152]
**Describe the bug**
I like the app and I am testing it out for purchase, but I am getting this issue every time:

Whenever I upload a new doc (either through the web portal or via paperparrot), I am unable to actually download the doc from the paperparrot app.  The app knows the doc exists and shows the correct preview, but when I click on it I get the error:

"Could not load document from server.  Are you connected to the internet?"

However, the connection is fine (I able to download it fine using a different app and on the web portal) just not on paperparrot.   What is even weirder, is that on occasion after I go back to the app after some time without changing anything, I am able to actually download the doc.  Also, sometimes it just says 0 bytes pdf instead.

**Environment(please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16.7.1
 - Version Latest
 - Server Version (if applicable) Latest

Running behind nginx proxy for https

**Comment by jrnewell** [comment]
Ha, as soon i type this out ... I am like I should check the ngnix logs and it appears to be a permission error.  Sorry for the spam

**Comment by LeoKlaus** [comment]
Oh, thanks for letting me know! Was just typing a response!
If you encounter issues in the future, there's a button to export logs in the settings tab of Paperparrot.

If you have any other questions, feedback or feature requests, feel free to let me know!
