### ISSUE TITLE
[Feature Request] search for ASN

### ISSUE THREAD

**Issue by slydlake** [LeoKlaus/Paperparrot#153]
Please add a option to search a ASN 😊

**Comment by LeoKlaus** [comment]
Hi Timon,

thank you very much for adding these on GitHub, makes tracking them a lot easier for me.
ASN search is pretty easy to implement and should ship with the next update!

**Comment by slydlake** [comment]
With the new RC1 of paperless, there is it possible to create new fields. So maybe this could be a part of this feature ☺️
