### ISSUE TITLE
[Feature Request] Recognize ASN Barcode

### ISSUE THREAD

**Issue by slydlake** [LeoKlaus/Paperparrot#154]
Maybe it is possible after a scan in the app and add it to paperless, to run only the barcode scanning from paperless itself.

**Comment by LeoKlaus** [comment]
Hi Timon,

this one could be a bit more complicated. As I personally don't use ASN barcodes, I don't really know the workflow with Paperless.
I'd imagine that Paperless would still look for barcodes in scanned documents if you upload them through the API (i.e. Paperparrot).

In what way do you scan documents with Paperparrot (i.e. camera, network scanner,..)?

Theoretically, VisionKit also supports barcodes, so it would be fairly easy to implement local recognition of ASN barcodes.

**Comment by slydlake** [comment]
Ha! You were right. Paperless takes my attributes that I set. And after processing paperless adds automatically the ASN Number 😁 So I think everything is fine. Maybe a little hint in the UI for this bei the ASN field?

**Comment by LeoKlaus** [comment]
Hey, thanks for updating this, glad it works!
It's probably worth a hint, yeah.
