### ISSUE TITLE
[BUG] Paperparrot Falsly Says Upload Success when I Can't Upload

### ISSUE THREAD

**Issue by jrnewell** [LeoKlaus/Paperparrot#157]
**Describe the bug**
Hey just want to say I love your app.

One nit i have is that it will give no indication that an upload failed.  My server runs on my local LAN under a certain VLAN.  Occasionally, I will try to upload a doc when connected to the wrong VLAN or on a public network and hence have no connectivity to my server.  However, Paperparrot doesn't really give me feedback that it failed, so I always have to double check if it worked.  If you have some time to kill, this would be a nice improvement.

**To Reproduce**
1. Go to a network not connected to server
2. Try to upload a doc

**Expected behavior**
An error message that the upload failed.

**Environment(please complete the following information):**
Device: iPhone X
OS: iOS 16.7.1
Version Latest
Server Version (if applicable) Latest
Running behind nginx proxy for https

**Comment by LeoKlaus** [comment]
Hi jrnewell,
thank you for reaching out and creating this issue. I'm glad you like Paperparrot!

My biggest priority right now is adding support for the new features in Paperless-ngx 2.0, but I'll see what I can do.
If I don't manage to fix this with the next release, it'll sure be with the one after that!

If you have any other feedback or suggestions, feel free to let me know!
