### ISSUE TITLE
Delete multible documents

### ISSUE THREAD

**Issue by Tomcad60** [LeoKlaus/Paperparrot#159]
Hello Leo

Thank you for your great work!
Can you consider adding a delete function when multiple documents are selected?
That would be very helpful for my paperless workflow!

Best regards 
Thomas

**Comment by Tomcad60** [comment]
Sorry, just saw, this is a dublet....

**Comment by Tomcad60** [comment]
Sorry, just saw, this is a dublet....

**Comment by LeoKlaus** [comment]
Hey Tomcad60,

thank you for reaching out!
I've actually already implemented this with the recent 1.9.0 update. This update is currently in TestFlight and should release later this week.

If you have any other suggestions or feedback, feel free to let me know!

**Comment by Tomcad60** [comment]
Hello Leo

Yes, I have another question that you might be able to explain to me through official channels.

The document date in the format dd.MMMM.YYYY (Switzerland) as the content of the document is always interpreted incorrectly for my first 20 definitely filed documents.
I think the US spelling is used for recognition...

Can this be changed?
Would be super useful!

**Comment by LeoKlaus** [comment]
> Hello Leo
> 
> Yes, I have another question that you might be able to explain to me through official channels.
> 
> The document date in the format dd.MMMM.YYYY (Switzerland) as the content of the document is always interpreted incorrectly for my first 20 definitely filed documents. I think the US spelling is used for recognition...
> 
> Can this be changed? Would be super useful!

Paperparrot should respect the locale set for your device for date recognition. I've changed the default date format to dd.MM.yyyy with version 1.8.1 of Paperparrot. The AppStore version will skip 1.8.1 and 1.9.0 and go straight to 2.0.0 later this week.

If this doesn't help, it should be possible to add an option in the settings to specify the preferred date format.
