### ISSUE TITLE
[BUG] Multi-Page Scans Using Camera Fail to Upload

### ISSUE THREAD

**Issue by greg-healy** [LeoKlaus/Paperparrot#162]
**Describe the bug**
The "Scan Using Camera" feature fails to upload the document to the server when more than one page is scanned.

**To Reproduce**
1. Go to Add
2. Click on Scan Using the Camera
3. Capture 2+ pages
4. Click Save
5. Enter details about the document
6. Click Upload

**Expected behavior**
The app returns to the Add menu and an info message with "Recent Server Tasks" should appear with the name of the uploaded document and a spinning wheel next to it. Once the upload completes the spinning wheel turns into a green checkmark in a circle.

**Actual Behavior**
No such info message appears nor does the file get uploaded to the server.

**Environment(please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.1.1
 - Version 2.0.0
 - Paperless-ngx Version 1.17.4

**Comment by LeoKlaus** [comment]
Hi Greg,
thank you for reaching out. In the current version of Paperparrot, error messages are missing for file uploads. I've already fixed this issue and am waiting for Apple to approve the update.

I suspect that the multi-page scans Paperparrot produces are larger than the maximum upload size your server accepts. Multi-page scans from within Paperparrot are just regular multi-page PDFs and I've just uploaded one successfully while testing.

Documents scanned with the camera can easily be 2-3MB per page, so a multi page document can easily exceed the default limits of many webservers.

Anyway, sorry for the inconvenience. Update 2.0.1 should drop shortly, which will bring back error messages for file uploads.

**Comment by greg-healy** [comment]
You're correct. Nginx limits the `client_max_body_size` of requests to 1M by default. Increasing that to 100M fixed the problem. Thanks for pointing me in the right direction!

https://github.com/jonaswinkler/paperless-ng/discussions/1617

**Comment by LeoKlaus** [comment]
Thanks for the update, glad it worked!

2.0.1 just dropped a few hours ago, so you should be able to see error messages from your server in case you ever run into issues again.

If you have any other feedback or suggestions, feel free to let me know!
