### ISSUE TITLE
[BUG] Custom Fields from Server

### ISSUE THREAD

**Issue by HSGEV** [LeoKlaus/Paperparrot#163]
Custom Field Attributs from Server Version 2.0.1 are not Sync with the App.

**Comment by LeoKlaus** [comment]
Hey HSGEV, thanks for reaching out.

Can you please go a little more in depth? When creating a custom field, adding it to a document and refreshing Paperparrot, I can see the newly created field just fine.

**Comment by HSGEV** [comment]
User was problem…

**Comment by LeoKlaus** [comment]
Thanks for the update :)
If you have any other feedback or suggestions, feel free to let me know!
