### ISSUE TITLE
[BUG] Can't see "Serveraufgaben" on an small Iphone screen (SE 2016)

### ISSUE THREAD

**Issue by MaximilianHerrmann** [LeoKlaus/Paperparrot#165]
**Describe the bug**
Apparently the screen drawing draws the four buttons (mit der kamera scannen, aus datei hochladen, etc) too bis, so that everything below "Serveraufgaben" cannot be seen. Just a very small part of a green dot is visible. 

**To Reproduce**
1. Go to 'Paperparrot App'
2. Click on 'Hinzufügen'
3. Scroll down to 'no scrolling is possible'
4. See error --> everything below Serveraufgaben is covered by the four buttons 'mit der kamera scannen' etc.

**Expected behavior**
I would either expect that the four buttons are small enought to see pending/completed jobs below 'Serveraufgaben'
or one could scroll down and see the pending/completed jobs.

**Screenshots**
![IMG_1336](https://github.com/LeoKlaus/Paperparrot/assets/95907779/7c85d37a-f6bf-4108-8639-6ace7eb2481f)

**Environment(please complete the following information):**
 - Device: iPhoneSE2016
 - OS: iOS15.7.9
 - Version 2.0.1
 - Server Version 1.9.2

**Additional context**

**Comment by LeoKlaus** [comment]
Good catch. I'll make sure to scale the buttons dynamically.

**Comment by LeoKlaus** [comment]
Just working on this, in the Simulator for the SE, it already scales properly. 
Do you use any text magnification or similar settings?
