### ISSUE TITLE
[Feature Request] Set a default import setting other than color

### ISSUE THREAD

**Issue by MaximilianHerrmann** [LeoKlaus/Paperparrot#166]
**Before submitting a feature request, please check whether a similar feature has already been requested [in the Discussions tab](https://github.com/LeoKlaus/Paperparrot/discussions/categories/feature-requests).**
If it has, you can vote for the request or add a comment if you think it could be expanded.

**Is your feature request related to a problem? Please describe.**
Importing documents from camera is mainly sufficient with black and white or greycolor.
Colored documents are rarely necessary.
Unfortunately the default setting for import after activating camera import is always "full color" import.

**Describe the solution you'd like**
Set a standart import setting for camera import that remains active after app restart either via
a) saving the options set in the camera import screen so they remain after app restart / next activation of camera import
b) creating an settings option for default import settings (color, bw, graycolor)

**Describe alternatives you've considered**
I considered importin all documents in colors, but prefer to save discspace

**Additional context**
none

Best Regards,

Max

**Comment by LeoKlaus** [comment]
Hey Maximilian, sorry for the late response.

Sadly, the built in VNDocumentCameraViewController that Paperparrot uses for scanning with the camera does not offer any api to change the default color space.

As I don't intend to build my own scanning logic or use a third party package, this is not something I am able to implement for now.

It would be possible to convert the scanned images to grayscale but I doubt the space savings are comparable to the built in grayscale / black and white options within the scanning view.
