### ISSUE TITLE
Share function does not work when connected via Tailscale

### ISSUE THREAD

**Issue by lastscoutboy** [LeoKlaus/Paperparrot#167]
**Describe the bug**
When using the share function to Paperparrot, e.g. to share a pdf from the file explorer on my iOS device it works as long as I have my paperless-ngx server connected locally. If I switch to my connection via Tailscale, that I use to access my paperless-ngx server from outside my network, I receive this error: "Server konnte nicht erreicht werden, bitte prüfe Deine Verbindung."
This is weird, as I can access all data via a Tailscale connection and I can also edit data fields.

**To Reproduce**
1. Go to share in lower left corner of e.g. the file browser on iOS (when connected to my paperless-ngx server via Tailscale)
2. Select Paperparrot as destination
3. Click  'Add document'
4. See error "Server konnte nicht erreicht werden, bitte prüfe Deine Verbindung."

**Expected behavior**
Instead of the error message, I expect a confirmation that the upload has worked.

**Screenshots**
![Bildschirmfoto 2023-12-20 um 14 56 24](https://github.com/LeoKlaus/Paperparrot/assets/31166095/72cebbbb-08ca-4e2e-a15d-534f480b94fc)

**Environment(please complete the following information):**
 - Device: iPhone13 mini
 - OS: iOS 17.2.
 - Version: 1
 - Server Version: Paperless-ngx 17.2.1

**Additional context**

**Comment by LeoKlaus** [comment]
Hi lastscoutboy, thanks for reaching out.

The share extension of an app on iOS is treated more like an individual app rather than a part of the app itself. Notably, this means that the share extension has its own set of entitlements and configuration options.

I've changed the transport security for the share extension with the last update of Paperparrot, in hopes of fixing this exact issue. 
When did you last try to upload a document via share? Can you confirm that you are running Paperparrot Version 2.1.1 and are still unable to upload documents? 
You can see the version in the settings tab of Paperparrot, by scrolling down and opening "About" or "Über Paperparrot".

**Comment by lastscoutboy** [comment]
Hi Leo,

Thank you very much for your super fast answer. I can confirm that I run the Paperparrot Version 2.1.1. The upload works, when I am locally connected in my network, yet it fails when I am connected via Tailscale, that I use to access the paperless server from remote. It is weird as all other functionality works fine via Tailscale connection.

Thanks for your help and the great app

Henning

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Leo Wehrfritz ***@***.***>
Gesendet: Wednesday, December 20, 2023 3:16:20 PM
An: LeoKlaus/Paperparrot ***@***.***>
Cc: lastscoutboy ***@***.***>; Author ***@***.***>
Betreff: Re: [LeoKlaus/Paperparrot] Share function does not work when connected via Tailscale (Issue #167)


Hi lastscoutboy, thanks for reaching out.

The share extension of an app on iOS is treated more like an individual app rather than a part of the app itself. Notably, this means that the share extension has its own set of entitlements and configuration options.

I've changed the transport security for the share extension with the last update of Paperparrot, in hopes of fixing this exact issue.
When did you last try to upload a document via share? Can you confirm that you are running Paperparrot Version 2.1.1 and are still unable to upload documents?
You can see the version in the settings tab of Paperparrot, by scrolling down and opening "About" or "Über Paperparrot".

**Comment by LeoKlaus** [comment]
I just realized that I put the entitlement for the share extension in the wrong place... I've just pushed an update, it should hit TestFlight fairly soon.
If you'd like to join the beta, just send me a mail at support@paperparrot.me

**Comment by lastscoutboy** [comment]
Hi Leo,

thanks a lot. I would love to join the beta.
All the best

Henning
________________________________
Von: Leo Wehrfritz ***@***.***>
Gesendet: Mittwoch, 20. Dezember 2023 17:01
An: LeoKlaus/Paperparrot ***@***.***>
Cc: lastscoutboy ***@***.***>; Author ***@***.***>
Betreff: Re: [LeoKlaus/Paperparrot] Share function does not work when connected via Tailscale (Issue #167)


I just realized that I put the entitlement for the share extension in the wrong place... I've just pushed an update, it should hit TestFlight fairly soon.
If you'd like to join the beta, just send me a mail at ***@***.******@***.***>

**Comment by lastscoutboy** [comment]
Hi Leo, thanks a lot for the amazing support. The updated version in TestFlight has solved the issue and now it works perfectly. This is a great app with an even better support.
Cheers Henning

**Comment by LeoKlaus** [comment]
Glad it worked! I'll close this and #164 then, I'll push the update to the AppStore at a later date.
