### ISSUE TITLE
[BUG] Trailing forward slash causes an error in Server address field

### ISSUE THREAD

**Issue by zelig2** [LeoKlaus/Paperparrot#173]
**Describe the bug**
Adding a trailing forward slash to the server field causes an error. 

**To Reproduce**
1. Go to Settings
2. Click on 'Manage connected Instances' ## 'connected' should be capitalized
3. Click on "Add Instance"
4. Add server name with a forward slash, plus the Username and Password
5. Click 'Connect'

**Expected behavior**
It should be able to handle a server address with or without a forward slash.

**Screenshots**
![4B7183C3-B099-4911-80DA-8740190F2F61_4_5005_c](https://github.com/LeoKlaus/Paperparrot/assets/1232415/6699b891-9d9e-45d5-a80c-f9c835567170)

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.1.2
 - Version 2.1.1
 - Server Version (if applicable) Paperless-ngx 2.2.1

**Additional context**
None

**Comment by LeoKlaus** [comment]
Good catch, I'll add an update for this.
