### ISSUE TITLE
[BUG] Owner information gets deleted

### ISSUE THREAD

**Issue by koseduhemak** [LeoKlaus/Paperparrot#179]
**Describe the bug**
Owner information is getting deleted when editing and saving a document via Paperparrot.

**To Reproduce**
Click on a document and edit it. Hit save.

**Expected behavior**
Owner is untouched (unless modified of course).

**Screenshots**

**Environment(please complete the following information):**
 - Latest version of Paperparrot (both on IPhone 17.2.1 and IPad 17.1.2)
 - Server Version Paperless-ngx 2.2.1

**Additional context**
I prefill the Owner of a document based on the document name and other heuristics on my paperless server.

**Comment by LeoKlaus** [comment]
I've tried this on two separate instances, both running Paperless-ngx 2.2.1 and couldn't reproduce the issue.

Could it be that this only happens with new documents or something similar? Can you check the permissions tab for the document in Paperparrot and verify that the correct owner is displayed there?

**Comment by koseduhemak** [comment]
You are right. I couldn't reproduce it. It was on newly created documents (processed by a template). But I tried again and it seems to work 😊. 
Sorry for bothering you with this, but thanks for looking into it!

**Comment by LeoKlaus** [comment]
> You are right. I couldn't reproduce it. It was on newly created documents (processed by a template). But I tried again and it seems to work 😊. Sorry for bothering you with this, but thanks for looking into it!

Great to hear and thanks for the update!
If you find a way to reproduce this, feel free to reopen.
