### ISSUE TITLE
[BUG] Sort tags alphabetically independent of capitalization

### ISSUE THREAD

**Issue by SirUli** [LeoKlaus/Paperparrot#181]
**Is your feature request related to a problem? Please describe.**
I do have most of my tags capitalized but some are in lower case as well (e.g. "eBay").  The current sorting has the capitalized ones at the top while the lower cased ones are under these.

**Describe the solution you'd like**
Sort tags alphabetically independent of capitalization

**Describe alternatives you've considered**
- Leave as is

**Comment by LeoKlaus** [comment]
Hey Uli,
thanks for reaching out! That's definitely not the intentional. I'll make sure to change this with the next update.
If you have any other feedback or suggestions, feel free to let me know!

**Comment by SirUli** [comment]
Wohoo great - thanks so much!

**Comment by LeoKlaus** [comment]
> Wohoo great - thanks so much!

I've just committed the change to the codebase.
I'm still working on some other smaller fixes and improvements so it might take a bit longer before this hits TestFlight and the AppStore.

**Comment by SirUli** [comment]
No worries at all - just seeing that feedback is incorporated is refreshing :)
