### ISSUE TITLE
[BUG] stuck on "received 25 documents"

### ISSUE THREAD

**Issue by stefnats** [LeoKlaus/Paperparrot#183]
**Describe the bug**
When I click on "perform full sync with server" it loads infinitely and it says "received 25 documents" and 5 minutes later "request times out"

**To Reproduce**
1. Go to settings
2. Click on perform full sync with server
3. See "received 25 documents"

**Expected behavior**
Should have consistent progress: 50, 75, 100, ... documents

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.2.1
 - Version 2.1.3
 - Server Version Paperless-ngx 2.4.3

**Comment by stefnats** [comment]
![image](https://github.com/LeoKlaus/Paperparrot/assets/1174473/98fe7719-f191-40c0-a489-977d62633892)

![image](https://github.com/LeoKlaus/Paperparrot/assets/1174473/c5cafb52-2ac0-42aa-9828-a6bb56a89676)

**Comment by stefnats** [comment]
![image](https://github.com/LeoKlaus/Paperparrot/assets/1174473/6919e8a6-5d26-4b58-826c-3675d84d7751)

![image](https://github.com/LeoKlaus/Paperparrot/assets/1174473/0eda71fe-d806-40db-9b0f-a8d19c661520)

**Comment by LeoKlaus** [comment]
Can export the debug logs after trying to sync?

**Comment by stefnats** [comment]
It doesn't seem like it. The spinning animation is there for ca 30 seconds and then the app doesn't respond :(

**Comment by LeoKlaus** [comment]
> It doesn't seem like it. The spinning animation is there for ca 30 seconds and then the app doesn't respond :(

What happens when you start the app? It should start a partial sync on launch. Does that work? Can you export logs after that?

For what reason are you trying to perform the full sync?

Do you have any rate-limiting or something similar on your server?

**Comment by LeoKlaus** [comment]
The underlying issue is the same as in #184. I'm closing this and will update the in other issue.

**Comment by stefnats** [comment]
You are right, it seems to be a reverse proxy related issue. It has the correct domain name, but I it's not https and the custom port (8000) is not in the "next" url. Reverse proxy is nginx, do you have any idea @LeoKlaus ?
