### ISSUE TITLE
[BUG] Stuck on Loading Tags from Server

### ISSUE THREAD

**Issue by SOCKEN** [LeoKlaus/Paperparrot#184]
hello,

sorry if I posted something wrong here. This is the first time I post a bug at Githup.

I have the problem on my Macbook that it stops at "Loading Tags from Server" When I do a full sync, it stops at 25 documents and then writes "Timeout on request" after some time
I work with a reverse proxy so that I can use HTTPS.
I have the problem on my Iphone Pro Max with the latest IOS, as well as on my Macbook, also in the latest version.

On the cell phone, the message "There seems to be no connection to the Internet" appears after 25 documents have been accessed shortly before.

What can I do?

**Comment by LeoKlaus** [comment]
Hey Socken,
Thank you for reaching out!

There's a button "Export Debug Logs" in the settings tab. Can you tap that after the sync has failed and send me the log?

Can you tell me which version of Paperless you're running and which reverse proxy?

**Comment by SOCKEN** [comment]
Here is the LOG:
The interesting thing is that it displays the internal, i.e. forwarded URL. This cannot work on the move.
But I wonder why this is the case?



[9.2.2024, 8:17] [CoreDataHandler] Initializing store for instance <private>
[9.2.2024, 8:17] [CoreDataHandler] CoreData store initialized
[9.2.2024, 8:17] [CustomQueryCoreDataHandler] Initializing store with iCloud support
[9.2.2024, 8:17] [CustomQueryCoreDataHandler] CoreData store initialized
[9.2.2024, 8:17] [StoreKitHandler] unlocked!
[9.2.2024, 8:17] [DocumentsView] Finished updating groups
[9.2.2024, 8:17] [DocumentsView] Finished updating users
[9.2.2024, 8:21] [ApiHandler] Enountered an error while fetching documents:
[9.2.2024, 8:21] [ApiHandler] Zeitüberschreitung bei der Anforderung.
[9.2.2024, 8:21] [ApiHandler] URL: https://192.168.100.180:8000/api/documents/?full_perms=true&order=descending&ordering=-id&page=2

I use Microsoft Server 2022 as reverse Proxy

**Comment by LeoKlaus** [comment]
Okay, I have a suspicion.

Can you head to [your-paperless-server]:[port]/api/documents/ and check the url that's given under "next"?

This should be the public facing URL of your server, not the private IP.
Paperparrot uses this URL for the second request, which would explain why the first one works.

Do you have the [PAPERLESS_URL env var](https://docs.paperless-ngx.com/configuration/#PAPERLESS_URL) set to the public URL of your server?

**Comment by SOCKEN** [comment]
Hi,

sorry, i don't understand this:
Can you head to [your-paperless-server]:[port]/api/documents/ and check the url that's given under "next"?

PAPERLESS_URL env: Yes, this is set to my public URL

Ah and i forgot, my Paperless Version is 2.4.3

**Comment by LeoKlaus** [comment]
No problem. What I meant is if your server url was https://paperless.mydomain.com, you should go to https://paperless.mydomain.com/api/documents/ (the last / is important) in your browser.

The site should look something like this:
![image](https://github.com/LeoKlaus/Paperparrot/assets/66492595/37d72caa-8da9-4e47-b2f8-89efefba9bac)

**Comment by SOCKEN** [comment]
Sorry i still don't get it. ;-)
Should i change my Reverse proxy or my DYNDNS or my Paperparrot Settings?

**Comment by LeoKlaus** [comment]
My bad, don't change anything.
Just open the api in your browser, as if you would access the Web UI.

**Comment by SOCKEN** [comment]
Ahh okay, here is what i got:

<img width="1217" alt="Bildschirmfoto 2024-02-09 um 08 58 20" src="https://github.com/LeoKlaus/Paperparrot/assets/11572536/2cda7e8c-9338-4194-9c06-c30b58427119">

**Comment by LeoKlaus** [comment]
Thanks for the update. Did Paperparrot ever work before or are you a new user?
I've just checked and can't reproduce the issue.

**Comment by SOCKEN** [comment]
No it don't work yet, so i'm a new user.
I also got the App "Paperless" on my phone and this one works fine but i like Paperparrot more ;-)

**Comment by LeoKlaus** [comment]
> I also got the App "Paperless" on my phone and this one works fine
As dar as I know, the Paperless app only displays the first page of results, i.e. 25 documents at most. Paperparrot works a bit different than most (all?) other Paperless clients in that it stores a complete local copy of the database to improve access speed and offline availability.

Does your proxy preserve the host header? It's been a while since I've worked with Windows Server (I guess you're using IIS?). The setting should be called `preserverHostHeader` and has to be set to true.
If this is set to false, Paperless will think that your request was made to `192.168.100.180` instead of the actual domain you're using. That's why Paperless returns the private IP in all api responses.

**Comment by SOCKEN** [comment]
host header, that was the right keyword. Now it works fine, thank you :-)

This was the Command for Windows Server to enable it.
%windir%\system32\inetsrv\appcmd.exe set config -section:system.webServer/proxy -preserveHostHeader:true /commit:apphost

**Comment by LeoKlaus** [comment]
Great to hear, thanks for the update! I believe this would also fix @stefnats issue #183.

If you have any other feedback or suggestions, feel free to let me know!
