### ISSUE TITLE
[BUG] Scrolling not possible in tag list

### ISSUE THREAD

**Issue by stepman0** [LeoKlaus/Paperparrot#193]
**Describe the bug**
When editing a documents properties, I cannot scroll in the lists of tags nor correspondents.

**To Reproduce**
1. Go to 'Documents'
2. Click on a document
3. Select the Tags list (has to be longer than the screen)
4. Try to scroll down

**Expected behavior**
Scrolling in the list being able to select a tag or correspondent starting with z.

**Screenshots**

**Environment(please complete the following information):**
 - Device: iPhone14 Plus
 - OS: iOS 17.3.1 (issue is there since some months)
 - Version 2.2.0
 - Server Version Paperless-ngx 2.5.3

**Additional context**

**Comment by stepman0** [comment]
Just checked, the issue also occurs on the iPad version.

**Comment by LeoKlaus** [comment]
Hey Stephan,

thanks for reaching out and sorry for the laughably late response.

I haven't been able to reproduce this on any of my devices or in the simulator. Did you wait for the synchronization process to finish before trying to add the tag?

There's an update on the way that introduces new menus for all attributes (with keyboard input), maybe those work better for you.
If you want to try the new version early, you can join the TestFlight beta for Paperparrot by heading to the bottom of the "Settings"-tab and tapping "Join the TestFlight-Beta".

The update should go live on the AppStore as well in the near future, I'm just trying to squash some bugs beforehand.

**Comment by LeoKlaus** [comment]
Closing this for now. If the issues appears again, please reopen.
