### ISSUE TITLE
[Feature Request] Change loading process / Add minimalistic server loading display

### ISSUE THREAD

**Issue by chrneu** [LeoKlaus/Paperparrot#195]
Right now when you open the app first thing what happens is that the server is being queried to load new entries. The app shows the current process and below a loading icon. As the loading information appears and disappears the home screen jumps a bit. 

My suggestions would be the following:
- Give an option to disable the update on start in the settings as a user might want to just have a quick look at the last entries. As a user could pull down to initiate the update he could do that later in the process
- Give an option to have instead of the full loading information just the loading indicator. You could move the loading information to the header, next to the server icon. Instead of the text, just show just show the loading indicator status. When completed display an update success item, when failed display an update failed icon

As a side remark, you could adjust the spacing of the loading indicator between the text and the tag as there is no spacing in direct to the tag.

**Comment by LeoKlaus** [comment]
> * Give an option to disable the update on start in the settings as a user might want to just have a quick look at the last entries. As a user could pull down to initiate the update he could do that later in the process

This one is pretty easy to implement, I'll see to have it done.

> As a side remark, you could adjust the spacing of the loading indicator between the text and the tag as there is no spacing in direct to the tag.

Sorry, but I don't really understand what you mean, are you talking about this spacing?
![Simulator Screenshot - iPhone 15 Pro - 2024-03-01 at 10 38 56](https://github.com/LeoKlaus/Paperparrot/assets/66492595/d8dd650d-3470-4153-8b13-deedf04a7865)
