### ISSUE TITLE
[Feature Request] Introduce quick add functionality

### ISSUE THREAD

**Issue by chrneu** [LeoKlaus/Paperparrot#196]
Right now the user has the possibility to press the add button which shows 4 options to add a new document. Some users may just want to use one option of it.

Maybe you could give a customization which action should be triggered when pressing the add button. 

Or, you could keep the existing functionality and introduce a long-press at the add button which opens a popup where a user could select the action.

I could also think of a combination of it, use just one action for the add button, but a long-press will display a popup with all actions.

What do you think?

**Comment by LeoKlaus** [comment]
Hey Christian, thanks for your suggestions!

Long presses on the items of the tab bar are something I have experimented with, but never found a workable solution with SwiftUI.

What I could do is implement a setting to chose what sheet to open automatically when heading to the "Add"-tab, something like this:
![Simulator Screen Recording - iPhone 15 Pro - 2024-03-01 at 10 32 30](https://github.com/LeoKlaus/Paperparrot/assets/66492595/df2fa6e3-0478-493c-a827-7e3167da3095)

**Comment by chrneu** [comment]
@LeoKlaus: I think I found an issue:

1) Took photo, started upload. 
2) As my instance is slow or the system has a high load, I wanted to check if the upload is still pending
3) Press back button to see the queue, shows now the result, but opens the camera again as the default option "camera" is selected. This is an infinite loop of pressing the button, seeing the queue for a second until the camera is opened again
4) After I change the default to ask everytime it shows it as normal

This brings me two my second question: Wouldn't it be better to separate the queue view to a dedicated area and display some additional information like:
- date&time
- upload speed
- required time
- history of uploaded entries

And related to this: When I am not connected to my home network, but I still wanted to take a photo, I cannot save it because of connectivity issues. Therefore it would be nice to keep the request as long in the queue until it was processed or cancelled. Right now I can just try it again or discard. But the photo is lost.
