### ISSUE TITLE
[BUG] Preview Pictures not showing up

### ISSUE THREAD

**Issue by dan3o3** [LeoKlaus/Paperparrot#197]
**Describe the bug**
It seems when Paperparrot is unable to retrieve/generate the preview pictures in the first time the pictures will never appear and show a spinning wheel forever. This seems to happen everytime when the redis server is unavailable and Paperparrot wants to retrieve new documents the first time from server. Unfortunately resync or any other does not help, only way to get the missing pictures was to delete the server and re-add it.

**To Reproduce**
1. Sync for new documents while redis server is down

**Expected behavior**
I would expect that with a full re-sync that spinning wheels disappear and document-preview pictures will appear.

**Environment(please complete the following information):**
 - Device: iPhone15pro
 - OS: iOS17.4
 - Version: 2.2.1
 - Server Version (if applicable):  Paperless-ngx 2.6.2

**Comment by LeoKlaus** [comment]
Hey dan3o3, thanks for the bug report!

I've heard this a few times in the past week or two. I wonder if something changed on the Paperless side, as this hasn't been an issue in the past year.

I'll see how I can implement this. Currently, the thumbnails are not loaded during the synchronization process but when the item first appears on screen (this drastically reduces the loading time on startup), and I'd like to keep it that way.

**Comment by dan3o3** [comment]
Thanks for your reply @LeoKlaus!
Wouldn’t it be an option to do that pic sync again only when you manually use the re-sync button in the options?

**Comment by LeoKlaus** [comment]
> Wouldn’t it be an option to do that pic sync again only when you manually use the re-sync button in the options?

Not really, as the preview download and metadata synchronization are completely separate processes. I think I'll either add some button to manually refresh the preview image or find another solution. Either way, I'll let you know once it's ready!

**Comment by LeoKlaus** [comment]
I've just released update 2.2.2 that includes a fix for this. If you still encounter this issue, let me know!
