### ISSUE TITLE
New Corespondent not working 

### ISSUE THREAD

**Issue by huggy024** [LeoKlaus/Paperparrot#198]
When adding a new corespondent after scanning a document, the field stays blank.  If you re type the corespondent, it’s not recognised.  However, after uploading the document you can add the corespondent then (it’s in the list).

1. Scan document 
2. Try adding a corespondent label
3. Field stays blank
4. Document uploads without corespondent label
5.  You can now add the corespondent label 

**Expected behavior**
Adding a new corespondent should allow the document to be uploaded with this label/field intact.

**Screenshots**

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: 17.4
 - Version: 2.2.1
 - Server Version: Paperless-ngx 2.63

**Comment by LeoKlaus** [comment]
Hey huggy,
thanks for reporting this! I've already noticed this issue and am working on a fix. This also applies to the search tab.
I'll let you know once I have more information!

If you find anything else or have other feedback, feel free to let me know!

**Comment by LeoKlaus** [comment]
I've just committed the fix, it will be released with the next update.

**Comment by huggy024** [comment]
That’s amazing, thank you.

Regards,

Nick.

**Comment by tribey2** [comment]
Awesome - I recently upgraded to Premium and this issue has been just about my only frustration, so glad to see it's being worked on!

**Comment by LeoKlaus** [comment]
> Awesome - I recently upgraded to Premium and this issue has been just about my only frustration, so glad to see it's being worked on!

Thank you for your support! I still have to take care of two other bugs but the update should go live on the AppStore soon. Until then, you may also use the TestFlight version by heading to settings and tapping "Join the TestFlight-Beta".

If you have any other feedback or suggestions, feel free to let me know!
