### ISSUE TITLE
Uploading multiple documents

### ISSUE THREAD

**Issue by glawleschkoff** [LeoKlaus/Paperparrot#199]
**Describe the bug**
In the Mac App, when uploading multiple documents, they do get imported properly but there is still an error notification at the end of the upload process. Internal app server used.

**To Reproduce**
1. Click "Hinzufügen"
2. Click "Aus Dateien hochladen"
3. Choose multiple files and click "öffnen"
4. Wait until the upload process is finished

**Expected behavior**
No error notification

**Screenshots**
<img width="707" alt="Bildschirmfoto 2024-04-02 um 11 30 56" src="https://github.com/LeoKlaus/Paperparrot/assets/38345970/616bbe3d-4804-41be-bded-c57b0e0f1b84">
**Environment(please complete the following information):**
 - Device: Macbook Air M2
 - OS: MacOS
 - Version: Sonoma 14.4.1
 - Server Version:

**Additional context**

**Comment by LeoKlaus** [comment]
Hey Glawleschkoff,

thanks for reporting this, I've been able to reproduce this on my mac. I'll let you know once I have a fix ready.

Should you have any other feedback or suggestions, feel free to let me know!

**Comment by LeoKlaus** [comment]
Update 2.2.2 is now live in the AppStore and includes a fix for this. You might have to manually look for the update to have it appear right away.
