### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leonardsellem** [LeoKlaus/Paperparrot#201]
**Describe the bug**
Cannot restore my purchase done on AppStore app from iOS Tesflight app v2.2.2 (345)

**To Reproduce**
1. Download app on App Store
2. Purchase to unlock all features
3. Join the beta on TestFlight
4. Download the app from Tesflight
5. Launch the beta app
6. In settings, click "restore purchases"
7. Fill in Apple ID password
8. Nothing happens

**Expected behavior**
Activation of all paid features (like Custom queries for example)

**Screenshots**
![image](https://github.com/LeoKlaus/Paperparrot/assets/2162208/ce57a0be-3e74-4bcc-9b09-1c06ca823321)

**Environment(please complete the following information):**
 - Device: iPhone 15 pro max
 - OS: iOS 17.5 beta (21F5048f)
 - Version 2.2.2 (345)
 - Server Version 2.7.2

**Comment by LeoKlaus** [comment]
Hey Leonard, thank you for reaching out!

This is expected. TestFlight doesn't support real in-app-purchases, so restoring them doesn't work either.

You can just "buy" the In-App-Purchase again, you won't be charged (the pop-up window will also confirm this).

**Comment by leonardsellem** [comment]
Sorry, I just read that I had to purchase it again, not being charged for it

**Comment by LeoKlaus** [comment]
I understand that this is really not intuitive, I will probably just disable the IAP for TestFlight releases.
