### ISSUE TITLE
[BUG] Custom queries tag filter uses OR instead of AND when adding multiple tags

### ISSUE THREAD

**Issue by jce-zz** [LeoKlaus/Paperparrot#203]
**Describe the bug**
Custom queries: When adding a tag filter consisting of multiple tags, the containing tags are not combined with "AND" but rather with "OR", i.e. undesired documents containing any of the tags are displayed in the results.

**To Reproduce**
1. Create an new custom query
2. Add a filter
3. Add more than one tag to the tag filter
4. Check the results of the query to find documents matching any of the tags instead of all of them

**Expected behavior**
The expectation is that adding multiple tags in the filter will only show documents containing ALL of the tags (AND condition), not any of the tags (OR condition). This is also suggested by the help text associated with the tag field in the filter screen.

**Environment(please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.3
 - Version 2.2.2
 - Server Version: Paperless-ngx 2.7.2

**Comment by LeoKlaus** [comment]
Hey jce-zz,
when creating a filter for a custom query, you can select whether to use "and" or "or" to filter by enabling the toggle below the tags field:
![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-12 at 10 24 19](https://github.com/LeoKlaus/Paperparrot/assets/66492595/146e0b4b-e339-4c6f-aecd-707644ceb921)

Though I see how this menu may not be very intuitive to use.

**Comment by jce-zz** [comment]
Ehm, yes, that makes actually a lot of sense. But as you said, I completely missed it in the UI... maybe the text could be improved and/or the option could be displayed permanently?
