### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by heimvon2** [LeoKlaus/Paperparrot#208]
**Describe the bug**
The app always wants to include the port (7645) during a full synchronization. However, the server is only accessible under a URL without this port. Example: https://paperless.example-server.com. When the app starts, it executes the whole thing as configured: https://paperless.example-server.com and loads the last 25 documents.

**To Reproduce**
1. Synchronize the documents.

**Expected behavior**
The synchronization should work without the port if it is not specified as part of the server URL.

**Screenshots**
![YVvg4ZQvvS](https://github.com/LeoKlaus/Paperparrot/assets/89463894/251252b8-9065-4e4d-b6cd-b264ce9e47cc)
![zdr5cfpRw2](https://github.com/LeoKlaus/Paperparrot/assets/89463894/9de3e706-2ad5-40fb-95a3-2b90f9a70e99)
![20240426_161520000_iOS](https://github.com/LeoKlaus/Paperparrot/assets/89463894/af534d70-25fa-41ce-9558-b3a18c5212f6)

**Environment:**
 - Device: iPhone15Pro
 - OS: iOS17.4.1
 - Version 2.2.2
 - Server Version 2.7.2

**Additional context**
The app works fine locally if a port has been entered.

**Comment by LeoKlaus** [comment]
Hey heimvon2, thanks for reaching out!

The url for the second page of documents is retrieved from your server (you can go to https://your-server.com/api/documents/ to verify this, the "next" key will probably be the exact URL that causes the task to fail in Paperparrot).

It's been a while since this popped up but I think setting ["PAPERLESS_URL"](https://docs.paperless-ngx.com/configuration/#PAPERLESS_URL) to the url you're using should fix the API responses and therefore this issue.

**Comment by heimvon2** [comment]
If I use https://paperless.example-server.com/api/documents/?full_perms=true&order=descending&ordering=-id&page2 in the browser, it works as well. The domain is stored in my "paperless_url."
![ciwdbf1Q4O](https://github.com/LeoKlaus/Paperparrot/assets/89463894/44d9e73f-950c-49b5-921f-10604b68e189)

How can I thoroughly examine the logs for errors in Paperparrot?

**Comment by LeoKlaus** [comment]
Did you add the port in the URL env var or is it just the protocol+domain?

If you open the API in the browser and look for the "next" attribute, is the port included in that link or not?

![image](https://github.com/LeoKlaus/Paperparrot/assets/66492595/d8fa6c9d-4409-42e1-b108-3779d71d83ac)

Paperparrot doesn't offer any more in-depth logging than the logs you've sent.

**Comment by LeoKlaus** [comment]
Can you check whether your reverse proxy properly forwards the host header?

For nginx, the directive should be
'proxy_set_header Host $host;'
For other proxies, you might have to look at the documentation. I remember another user had this issue using IIS as a reverse proxy.

**Comment by heimvon2** [comment]
That helped me a bit further. Indeed, it says "next http://paperless.example-server.net:7645/api/documents/?full_perms=true&order=descending&ordering=-id&page=2&page2=." I used http://paperless.example-server.net/api/documents/?full_perms=true&order=descending&ordering=-id&page=2&page2= in the browser, as it's always used there. Then I'll have to see how I implement the whole thing. I'm using a Cloudflare tunnel with HomeAssistant.

**Comment by heimvon2** [comment]
Have you ever heard of anything related to Cloudflare Tunnel and Paperparrot with HomeAssistant?

**Comment by LeoKlaus** [comment]
I remember one person using the HA-Addon, but I think they switched to a regular docker installation.

The add-on developer [seems to be aware of the issue](https://community.home-assistant.io/t/benoit-anastay-add-on-paperless-ngx/664789/26) but I haven't found any mention of it after that post.

Are you using the "direct access" for the addon (exposing a port for Paperless)?

If so, is the tunnel pointing at that port?

I do recall some people using Paperparrot with CF tunnels without issues, so I'm assuming the tunnel itself is not the issue.

**Comment by heimvon2** [comment]
Yes, that's actually my own issue that you linked to :) I'll get in touch with Benoit. It's definitely not a problem with your app or the tunnel. Thanks for your help.

**Comment by heimvon2** [comment]
![hLdO1g2PDL](https://github.com/LeoKlaus/Paperparrot/assets/89463894/008cfdfc-0b02-4f65-9614-557d26564a34)
![sh2WNvQiDX](https://github.com/LeoKlaus/Paperparrot/assets/89463894/78e2fab4-c10d-40f8-871b-4d4ec3ea122c)



This is the Cloudflare Tunnels Config. So yes, the tunnel pointing at that port.
