### ISSUE TITLE
[BUG] Connection fails in WiFi only

### ISSUE THREAD

**Issue by zweckj** [LeoKlaus/Paperparrot#209]
**Describe the bug**

I can't connect to the server while being connected to the WiFi. In the browser the connection works fine, and when switching to mobile data it works as expected as well. Debug Logs attached. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - Device: [e.g. iPhone6] IPhone15
 - OS: [e.g. iOS8.1] 17.4.1
 - Server Version (if applicable) [e.g. Paperless-ngx 1.11.3]

**Additional context**

[27.4.2024, 8:51] [ApiHandler] Received invalid data for preview image...
[27.4.2024, 8:51] [ApiHandler] Received invalid data for preview image...
[27.4.2024, 8:51] [ApiHandler] Received invalid data for preview image...
[27.4.2024, 8:51] [ApiHandler] Error updating document Optional(Error Domain=NSURLErrorDomain Code=-1009 "Es besteht anscheinend keine Verbindung zum Internet." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x303eff030 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns, uses wifi, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C051DBAE-6C8E-4811-9806-BBB6F8C7FCE8>.<18>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C051DBAE-6C8E-4811-9806-BBB6F8C7FCE8>.<18>"
), NSLocalizedDescription=Es besteht anscheinend keine Verbindung zum Internet., NSErrorFailingURLStringKey=https://paperless.REDACTED/api/documents/post_document/, NSErrorFailingURLKey=https://paperless.REDACTED/api/documents/post_document/, _kCFStreamErrorDomainKey=1})
[27.4.2024, 8:51] [ApiHandler] Error updating document Optional(Error Domain=NSURLErrorDomain Code=-1009 "Es besteht anscheinend keine Verbindung zum Internet." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x303eca040 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns, uses wifi, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <FC4E3A95-2800-4019-9D5F-C483C3207EDA>.<19>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <FC4E3A95-2800-4019-9D5F-C483C3207EDA>.<19>"
), NSLocalizedDescription=Es besteht anscheinend keine Verbindung zum Internet., NSErrorFailingURLStringKey=https://paperless.REDACTED/api/documents/post_document/, NSErrorFailingURLKey=https://paperless.REDACTED/api/documents/post_document/, _kCFStreamErrorDomainKey=1})
[27.4.2024, 8:52] [UploadPreviewView] Deleted file: <private>

**Comment by LeoKlaus** [comment]
Hey Josef, thanks for reaching out!

Can you make sure that local network access is enabled in the settings?
![image](https://github.com/LeoKlaus/Paperparrot/assets/66492595/3a808ddd-66d6-4403-bc08-954357b22162)

**Comment by zweckj** [comment]
Can confirm it’s enabled

**Comment by LeoKlaus** [comment]
Maybe try reinstalling the app/restarting the phone and make sure local network access is enabled when setting it up again.

Another possible issue could be dns rebind protection being enabled in your router.

Error Domain=NSURLErrorDomain Code=-1009 is thrown by the OS / the default URLSession, so there is something preventing your phone from connecting to your server in your network.
It's interesting that it works in Safari, but that may be caused by iCloud private relay causing you to involuntarily connect remotely instead of a locally.

**Comment by zweckj** [comment]
> Maybe try reinstalling the app/restarting the phone and make sure local network access is enabled when setting it up again.

First thing I did, no change.

> Another possible issue could be dns rebind protection being enabled in your router.

 Nope. 

> Error Domain=NSURLErrorDomain Code=-1009 is thrown by the OS / the default URLSession, so there is something preventing your phone from connecting to your server in your network. It's interesting that it works in Safari, but that may be caused by iCloud private relay causing you to involuntarily connect remotely instead of a locally.

would have been my first guess as well, but since it’s working in Safari it’s weird. private relay is off though and other apps (like immich) have no problem with the DNS rebind

**Comment by LeoKlaus** [comment]
Can you try adding your server via the private IP?

Paperparrot is only using standard URLSessions, so I doubt it's a matter of implementation, I just don't understand why the OS would block those network calls. I've seen the same issue pop up recently in another app, but in that case the local network access was the cause.

**Comment by zweckj** [comment]
It's super weird. IP doesn't work (only in the app) either

**Comment by LeoKlaus** [comment]
This screams local network access.
Stupid question but have you tried disabling and re-enabling local network access in the settings?

**Comment by zweckj** [comment]
Agreed, but clueless what to do. Yep I tried that.

**Comment by LeoKlaus** [comment]
If restarting the phone didn't help either, I don't know what else to do.

I can confirm it's not a general issue with Paperparrot, it works in my local network with multiple devices.
I can reliably reproduce the issue (same errors in the logs) by disabling local network access, however.

**Comment by zweckj** [comment]
I'd agree, but it’s super weird that it’s only an issue with Paperparrot (across different phones) all the other self hosted apps are working just fine.

**Comment by zweckj** [comment]
on a 3rd phone it works (different iCloud backup) so it's indeed something weird in my phone. Thanks for your help!

**Comment by LeoKlaus** [comment]
> on a 3rd phone it works (different iCloud backup) so it's indeed something weird in my phone. Thanks for your help!

That's insane. I'm hoping this will be resolved with the next iOS update...
