### ISSUE TITLE
[BUG] Get Bad URL when using reverse proxy with 1.111b domain (paperless.12345678.xyz)

### ISSUE THREAD

**Issue by Hellaren** [LeoKlaus/Paperparrot#220]
**Describe the bug**
The app works fine in the local network when connecting via IP:PORT (ex: 192.168.50.123:8090).
In order to access paperless from internet the following actions have been done:
1. Purchased a domain in 1.111b domain space (ex: 12345678.xyz)
2. Set up a Tunnel to my network via CloudFlare ZeroTrust, so my public url looks like docmanagement.12345678.xyz.
3. Paperless was configured to work with public domains.
4. Confirmed that paperless is available in Browser via docmanagement.12345678.xyz.

When adding a new server instance that points to `docmanagement.12345678.xyz.`, the validation fails with error message "bad URL"

**To Reproduce**
1. Go to Settings -> Manage Connected Instances -> Add Instance
2. Set protocol: https://
3. Set Url: docmanagement.12345678.xyz (**note: the domain name has been redacted for the privacy purposes**).
4. Set Username, Password for paperless user account.

**Expected behavior**
The app allows adding a new instance with public URL and no ports.

**Screenshots**
![image](https://github.com/user-attachments/assets/b628e1fe-4571-4f57-96c6-a05a877c711b)

**Environment(please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: 18.0.1
 - App Version 2.4.2
 - Server Version (if applicable) Paperless-ngx 2.12.0

**Comment by LeoKlaus** [comment]
I've tried reproducing this, but neither my physical iPhone nor the simulator running iOS 18.0 or 18.1 threw this error. When using the domain example you gave, I ended up receiving timeouts, which are probably expected.

Does opening the webinterface work in Safari on your iPhone?

**Comment by Hellaren** [comment]
Hey @LeoKlaus, thanks for your reply

I've tried to reproduce the issue again and couldn't.
The URL worked just fine and I was able to connect to the server. Didn't expect that a restart would solve this since I thought it had been a genuine validation issue.

Thanks!

**Comment by LeoKlaus** [comment]
Thank you for the update and happy to hear it works now!
Weird issue, all URL validation is done with built-in Swift tools...
