### ISSUE TITLE
[Feature Request] negative sign and comma to fill user-defined fields

### ISSUE THREAD

**Issue by tonyblue2** [LeoKlaus/Paperparrot#221]
Hello, 

I'm using PaperParrot with Paperless-ngx. On paperles-ngx, user-defined fields are defined, e.g. for the invoice amount. 

If I now want to fill the custom field with Paperparrot, a pure number keyboard opens on the iPhone. 

* It is not possible to enter a negative sign ("-") e. g. -100. 
* It is also not possible to enter a comma (",") to enter amounts, e.g. 5, 23, because the keyboard that appears does not contain a comma. 

It would be great if Paperparrot opened a keyboard that contains both a minus ("-") and a comma (",") to label user-defined fields. 

Thank you very much! 

Tony

**Comment by LeoKlaus** [comment]
Hey Tony,

thank you very much for reporting this. As far as I can tell, this and #219 are about the same issue, so I'm closing this one. If I got you wrong, feel free to reopen this.
