### ISSUE TITLE
Image display issue - image goes beyond dock, preventing save action

### ISSUE THREAD

**Issue by alex90do** [LeoKlaus/Paperparrot#225]
Describe the bug
The image is not fully displayed and extends beyond the dock, making it impossible to save.

To Reproduce

Open Paperparrot.
Load an image for editing.
Observe that the image is cut off at the bottom and goes beyond the dock.
Attempt to save the image and notice that you cannot access the save option.
Expected behavior
The image should be fully visible within the editing area, allowing the user to see the entire image and access the save option without obstruction.

Screenshots

(Add any relevant screenshots to illustrate the problem.)

Environment (please complete the following information):

Device: MacBook Pro 2019
OS: macOS 15.0.1

Additional context
This issue may affect usability, especially for users who need to save images frequently. It would be helpful to check if resizing the application window or changing display settings affects the behavior.

**Comment by alex90do** [comment]
![Bildschirmfoto 2024-10-30 um 10 42 42](https://github.com/user-attachments/assets/07625d58-396c-43d6-847d-def4e1895571)

**Comment by LeoKlaus** [comment]
I tried to reproduce this, but the sheet always stays within the bounds of the screen on my machine. The content of the sheet (the image preview and metadata fields) are in a scrollable container.

Can you give me the exact steps you took to make this happen (i.e. using drag&drop, the photo picker, etc.)?

**Comment by alex90do** [comment]
hmm... thats funny, i reinstalled the app and now it looks different & works fine... 
![Bildschirmfoto 2024-10-31 um 11 09 21](https://github.com/user-attachments/assets/b9b02726-bf18-42b4-a9c5-e2c765f03c9e)

**Comment by LeoKlaus** [comment]
This is how it's supposed to look, super weird.
