### ISSUE TITLE
[Feature Request] Explain what features the paid version provides

### ISSUE THREAD

**Issue by andi0b** [LeoKlaus/Paperparrot#226]
I've connected Paperparrot iPadOS with my Pngx server, the app looks really good. I'm totally considering to buy the full version.

But actually I'm a bit unsure what the features will be. More than 5 documents is easy to guess. But what do custom queries do? I can't really get an idea before buying it. Are there other paid features?

It would be great to get a list of paid features and what they actually do, either inside the app or on the website. Even if it's just 5 bullet points.

What I'm really missing for now: more columns in the document list. Does it come with the paid version?

**Comment by LeoKlaus** [comment]
Apart from custom queries and the document limit, there is no difference in the free and paid version of Paperparrot. The number of columns in the document list is depending on the size of your screen (or the window on Mac), there's currently no way to change the size of the previews, but you can switch to a list or a table view in the settings tab.

Custom queries allow you to group search results, for example by month or week of year and display the results as a bar chart. Basically, they're saved views with the option to group results. You can use them to get an overview of how many documents were added per week, for example:
![image](https://github.com/user-attachments/assets/f8cf051a-cc73-4c92-a775-cfa85f6da85f)
