### ISSUE TITLE
[BUG] Incorrect Keyboard Layout for Numerical Data Netry

### ISSUE THREAD

**Issue by sudonem** [LeoKlaus/Paperparrot#228]
**Describe the bug**
The keyboard layout provided when entering numbers into a custom field that is a "monetary" type doesn't allow entering periods or commas, or automatically formatting based on county setting, which means there is no way to make a distinction between 9.99, or 999.

**To Reproduce**
1. Assign a custom field to a paperless document with the "monetary" type
2. Open the document in Paper Parrot
3. Attempt to enter a monetary / financial value. 
4. See incorrect formatting. 

**Screenshots**
![image](https://github.com/user-attachments/assets/e7f4051d-a6fb-4b32-a805-32015c99c98b)

**Environment(please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.7

**Comment by LeoKlaus** [comment]
Hi sudonem,

thank you for reaching out! There already is an issue for this at #219, so I'll close this one.

I've already implemented a fix for this with the latest TestFlight release, it should hit the AppStore soon.
