### ISSUE TITLE
[Feature Request] Adjustable Document Preview Size

### ISSUE THREAD

**Issue by bandundu** [LeoKlaus/Paperparrot#230]
### Summary:
Add a zoom bar to adjust the size of document thumbnails in the documents and inbox view. This would allow users to enlarge or shrink the document previews based on their needs.

### Problem:
Currently, document previews are fixed in size, making it difficult to get a “Quick Look” at documents without opening them. Having a larger preview is more helpful than relying on document titles or other metadata, especially when titles are generic or unhelpful (e.g., scan.9484).

### Proposed Solution:
Implement a zoom bar or slider to dynamically resize document previews. This feature would:
	•	Enable users to focus more on the visual content of documents.
	•	Adapt the UI to different workflows, whether prioritizing overview or detail.

**Comment by LeoKlaus** [comment]
Hi Charles, thank you for the suggestion! On iOS, the context menu shows an enlarged preview, maybe that could already suit your needs?

![image](https://github.com/user-attachments/assets/66064264-7445-4b0a-a83b-1e455dc5b1d9)

**Comment by bandundu** [comment]
Hi Leo,

apologies for not being specific enough. I was talking about the Mac application. Here I would prefer to be able to see the documents e.g in a 4x4 grid with bigger previews instead and to control that a "zoom" slider would be nice

![image](https://github.com/user-attachments/assets/a0f78310-cc58-41a9-8cb8-044daebc9bce)

**Comment by LeoKlaus** [comment]
I see, thank you for the clarification. This shouldn't be too hard to add, the preview size is technically already dynamic.

**Comment by LeoKlaus** [comment]
I released an update to TestFlight yesterday that includes an option to scale the preview size.

**Comment by bandundu** [comment]
Thank you for the super quick response time!
