### ISSUE TITLE
[BUG] Unable to cancel tag creation

### ISSUE THREAD

**Issue by dominicpratt** [LeoKlaus/Paperparrot#85]
**Describe the bug**
When adding a new document, you can click in the "Tags" field to create a new tag. If you do this by mistake and do not want to create a new tag, it is impossible to close the window or even Paperparrot.

**To Reproduce**
1. Add a new document
2. klick in "Tags" field, select "Add tag (Tag hinzufügen in German)"
3. try to cancel that window without creation a new tag

**Expected behavior**
A "X" or "Cancel"-Button to close that windows

**Screenshots**
![Bildschirm­foto 2023-03-03 um 17 33 17](https://user-images.githubusercontent.com/14056131/222775424-9b8fbd33-eaba-436e-85e9-a29e75ee5c35.png)

**Environment(please complete the following information):**
 - Device: iMac M1
 - OS: macOS 13.2.1 (22D68)
 - Version 1.0.0 (127)
 - Server Version: Paperless-NGX 1.13.0

**Comment by LeoKlaus** [comment]
Good catch, thanks for the report. This issue actually applies to all modals on Mac
