### ISSUE TITLE
Tags, filter, etc are not sorted by name

### ISSUE THREAD

**Issue by ronaldheft** [LeoKlaus/Paperparrot#86]
**Describe the bug**
The tag list and filter list appear to be sorting by creation date and not by name.

**Expected behavior**
Lists should sort alphabetically or at least have the option.

**Screenshots**
![image](https://user-images.githubusercontent.com/1143112/226149386-7eaf8ede-5eb5-4de5-847d-332c623520fb.png)
![image](https://user-images.githubusercontent.com/1143112/226149389-4f43ed1e-2812-403b-a7f6-0530142aa11f.png)

**Comment by LeoKlaus** [comment]
Hey Ron, thanks for the report. 
I've already made this change but am still working on some other things before submitting the update to Apple.
I'll keep the issue open until I submit the update.

**Comment by ronaldheft** [comment]
Thanks for the update! Loving the app thus far!

**Comment by LeoKlaus** [comment]
Version 1.2.1 is now available for MacOS and iOS. From this version on, all attributes are sorted alphabetically.
