### ISSUE TITLE
[Feature Request] reset server

### ISSUE THREAD

**Issue by s4msy** [LeoKlaus/Paperparrot#88]
**Is your feature request related to a problem? Please describe.**
I made the first setup with Server A, but I killed this server and setup a Server B with a different FQDN. But there is no chance to revert the Setup with Server A.

**Describe the solution you'd like**
The possibility to reset the Server Settings.

**Describe alternatives you've considered**
A wiki entry how to remove manually the saved settings, on MacOS there are only some sqlite files, which doesnt affect the settings of the connected server.

**Additional context**
The app even recognize the missing Server A. It doesnt exist anymore, paperparrot doesnt checked the state of the server. If the connection is lost, an automatically call for renewing server-settings would be appreciate.

**Comment by LeoKlaus** [comment]
Version 1.2.1 is now available for MacOS and iOS, this update adds a new button in settings to switch server.
