### ISSUE TITLE
OCR from the original file is read

### ISSUE THREAD

**Issue by Der-Norden** [LeoKlaus/Paperparrot#89]
**Describe the bug**

If a scanned file with existing OCR is imported into Paperless ngx, which is re-OCRed via Paperless because it is incorrect in the original file, the app will still show the OCR from the original file.

**To Reproduce**
GERMAN:

Importiere eine Datei welche eine fehlerhafte OCR besitzt. Im Zeitpunkt der Importierung muss auf dem Paperless ngx Server in der entsprechenden Config der Parameter wie folgt aussehen: PAPERLESS_OCR_MODE=redo

Nur dann wird eine Datei welche OCR beinhaltet erneut eingelesen. Zu lesen unter folgendem Link:

https://docs.paperless-ngx.com/configuration/#ocr

Nachdem die Datei eingelesen ist, kann man beide Dateien also sowohl das original wie auch das neue von Paperless ngx erstellte über die Web-Oberfläche von Paperless herunterladen.

Die fehlerhafte OCR aus der originalen Datei kann nun mit der neu erstellten verglichen werden.

Man kann auch in Paperless in der jeweiligen Datei unter Bearbeiten und Inhalt den eingelesenen Text sehen.

Wenn man nun festgestellt hat in der originalen Datei und der von Paperless erstellten unterschiedliche OCR Versionen zu haben, kann man aus der App aus der jeweiligen Datei einen Textinhalt kopieren welcher in beiden Dateien anders sein sollte. Dann stellt man fest, es wird die OCR Ebene aus der originalen gelesen.

ENGLISH:

Import a file that has an incorrect OCR. At the time of import, the parameter must look like this in the corresponding config on the Paperless ngx server: PAPERLESS_OCR_MODE=redo

Only then will a file containing OCR be read in again. To read under the following link:

https://docs.paperless-ngx.com/configuration/#ocr

After the file has been read in, you can download both files, both the original and the new one created by Paperless ngx, via the Paperless web interface.

The incorrect OCR from the original file can now be compared with the newly created one.

You can also see the read text in Paperless in the respective file under Edit and Content.

If you have now determined that the original file and the one created by Paperless have different OCR versions, you can copy text content from the app from the respective file which should be different in both files. Then you realize that the OCR level is read from the original.

**Expected behavior**
I expect the OCR which is also used by Paperless. If it can be adjusted or both are possible, this would certainly be better.

**Comment by LeoKlaus** [comment]
Thank you for the report. I don't quite understand what you mean, though.

If you upload a document through Paperparrot, the app OCRs the document and that content is wrong?

Would an option to disable local OCR before uploading fix your issue?

**Comment by LeoKlaus** [comment]
I'm closing this for now. If the issue persists, please elaborate what exactly I could do to fix it.
